// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN33IifpkfGAaDKrsvvKSslOXNJ6zc5pQ',
    appId: '1:183979120874:web:cb89e6af183220e4c21f93',
    messagingSenderId: '183979120874',
    projectId: 'whatchat-15169',
    authDomain: 'whatchat-15169.firebaseapp.com',
    storageBucket: 'whatchat-15169.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmEImu1PcmoVp9j_2SbTB-EnOejN3Gcco',
    appId: '1:183979120874:android:700e389ece65a2d6c21f93',
    messagingSenderId: '183979120874',
    projectId: 'whatchat-15169',
    storageBucket: 'whatchat-15169.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzI1kMLXs4h8CPUuViCN32tkIaxIqIl6M',
    appId: '1:183979120874:ios:68b9ebf89b650321c21f93',
    messagingSenderId: '183979120874',
    projectId: 'whatchat-15169',
    storageBucket: 'whatchat-15169.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzI1kMLXs4h8CPUuViCN32tkIaxIqIl6M',
    appId: '1:183979120874:ios:68b9ebf89b650321c21f93',
    messagingSenderId: '183979120874',
    projectId: 'whatchat-15169',
    storageBucket: 'whatchat-15169.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN33IifpkfGAaDKrsvvKSslOXNJ6zc5pQ',
    appId: '1:183979120874:web:9fa923a21769c890c21f93',
    messagingSenderId: '183979120874',
    projectId: 'whatchat-15169',
    authDomain: 'whatchat-15169.firebaseapp.com',
    storageBucket: 'whatchat-15169.firebasestorage.app',
  );
}
